apiVersion: v1
kind: Service
metadata:
  name: headless-svc
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: 2380
      name: etcd-server-ssl
    - port: 2379
      name: etcd-client-ssl
