apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts
spec:
  serviceName: headless-svc
  podManagementPolicy: Parallel
  replicas: 1
  template:
    metadata:
      name: etcd
    spec:
      containers:
        - name: etcd
          image: etcd
          command:
            - "/bin/sh"
            - "-ec"
            - |
              for env_var in $(env|grep -E '^ETCD_'); do
                eval "export ${env_var}"
              done

              # This is a hack to allow all replicas to be created before etcd
              # is run. Required for proper DNS SRV bootstrapping.
              sleep 10s

              exec etcd
          envFrom:
            - configMapRef:
                name: cm
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: datadir
              mountPath: /var/lib/etcd
            - name: tls
              mountPath: /etc/kubernetes/pki/etcd
              readOnly: true
          ports:
            - containerPort: 2379
              name: client
            - containerPort: 2380
              name: peer
          readinessProbe:
            exec:
              command:
                - etcdctl
                - endpoint
                - health
          livenessProbe:
            exec:
              command:
                - etcdctl
                - endpoint
                - health
      volumes:
        - name: datadir
          emptyDir: {}
        - name: tls
          secret:
            defaultMode: 420
            secretName: etcd-certs
