apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: hyperkube
    newName: k8s.gcr.io/hyperkube
    newTag: v1.16.2

resources:
  - deploy.yaml
  - pdb.yaml
  - svc.yaml

namePrefix: kube-scheduler-

commonLabels:
  app.kubernetes.io/name: kube-scheduler

commonAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: "/metrics"
  prometheus.io/port: "10251"
  prometheus.io/scheme: "http"
