apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: read-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeless-controller-read-clusterrole
subjects:
  - kind: ServiceAccount
    name: kubeless-controller-sa
    namespace: kube-system
