apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  replicas: 1
  template:
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      containers:
        - name: kube-controller-manager
          image: hyperkube
          command:
            - kube-controller-manager
            - --authentication-kubeconfig=/etc/kubernetes/controller-manager.conf
            - --authorization-kubeconfig=/etc/kubernetes/controller-manager.conf
            - --bind-address=0.0.0.0
            - --client-ca-file=/etc/kubernetes/pki/ca.crt
            - --cluster-signing-cert-file=/etc/kubernetes/pki/ca.crt
            - --cluster-signing-key-file=/etc/kubernetes/pki/ca.key
            - --controllers=*,bootstrapsigner,tokencleaner
            - --kubeconfig=/etc/kubernetes/controller-manager.conf
            - --leader-elect=true
            - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
            - --root-ca-file=/etc/kubernetes/pki/ca.crt
            - --service-account-private-key-file=/etc/kubernetes/pki/sa.key
            - --use-service-account-credentials=true
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: 10257
            initialDelaySeconds: 15
            timeoutSeconds: 15
          volumeMounts:
            - name: certs
              mountPath: /etc/kubernetes/pki
              readOnly: true
            - name: kubeconfigs
              mountPath: /etc/kubernetes
              readOnly: true
          ports:
            - name: http-metrics
              protocol: TCP
              containerPort: 10252
          resources:
            requests:
              memory: "500Mi"
              cpu: "250m"
            limits:
              memory: "1000Mi"
              cpu: "500m"
      volumes:
        - name: certs
          secret:
            secretName: k8s-certs
        - name: kubeconfigs
          secret:
            secretName: kubeconfigs
