apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      group: apps
      version: v1
      labelSelector: "app.kubernetes.io/name=etcd"
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      group: apps
      version: v1
      labelSelector: "app.kubernetes.io/name=kube-apiserver"
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      group: apps
      version: v1
      labelSelector: "app.kubernetes.io/name=kube-controller-manager"
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      group: apps
      version: v1
      labelSelector: "app.kubernetes.io/name=kube-scheduler"
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
