apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: kubeless-function-controller
    newName: docker.io/kubeless/function-controller
    newTag: v1.0.5
  - name: kubeless-http-trigger-controller
    newName: docker.io/kubeless/http-trigger-controller
    newTag: v1.0.1
  - name: kubeless-cronjob-trigger-controller
    newName: docker.io/kubeless/cronjob-trigger-controller
    newTag: v1.0.1

resources:
  - deploy.yaml
  - sa.yaml
  - rolebinding.yaml

namePrefix: kubeless-controller-

commonLabels:
  app.kubernetes.io/name: kubeless-controller
